DROP TABLE IF EXISTS CLOTHES_TYPE;

CREATE TABLE CLOTHES_TYPE (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL UNIQUE,
    layer VARCHAR(255) NOT NULL,

    PRIMARY KEY (id)
);
